//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homework
    {
        public int HomeworkId { get; set; }
        public int StudentId { get; set; }
        public int ChapterId { get; set; }
        public int HomeworkTypeId { get; set; }
        public Nullable<int> ScoreId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> YXZJId { get; set; }
        public int UploadFileId { get; set; }
        public int Speed { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        public virtual HomeworkType HomeworkType { get; set; }
        public virtual Score Score { get; set; }
        public virtual Student Student { get; set; }
        public virtual UploadFile UploadFile { get; set; }
        public virtual YXZJ YXZJ { get; set; }
    }
}
