//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Homework = new HashSet<Homework>();
            this.UploadFiles = new HashSet<UploadFile>();
        }
    
        public int StudentNo { get; set; }
        public string StudentId { get; set; }
        public string StudentName { get; set; }
        public string Password { get; set; }
        public string StudentNamePinyin { get; set; }
        public bool GenderId { get; set; }
        public string IdCardNo { get; set; }
        public Nullable<int> ClassId { get; set; }
        public int EduId { get; set; }
        public string GraduateSchool { get; set; }
        public string Major { get; set; }
        public string Phone { get; set; }
        public string FamilyName { get; set; }
        public string FamilyPhone { get; set; }
        public string Adress { get; set; }
        public string Remark { get; set; }
        public bool Status { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<Homework> Homework { get; set; }
        public virtual ICollection<UploadFile> UploadFiles { get; set; }
    }
}
