//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YXZJ
    {
        public YXZJ()
        {
            this.Homework = new HashSet<Homework>();
        }
    
        public int YXZJId { get; set; }
        public string Y_Have { get; set; }
        public string Y_NotHave { get; set; }
        public string Z_Have { get; set; }
        public string Z_NotHave { get; set; }
    
        public virtual ICollection<Homework> Homework { get; set; }
    }
}
